### ISSUE TITLE
typo in tests

### ISSUE THREAD

**Issue by Trophime** [PierreMarchand20/htool#3]
in tests/performance_tests/hmat.hpp

```
In file included from /build/htool-0.1~git20191218/tests/performance_tests/hmat_fullACA.cpp:2:
/build/htool-0.1~git20191218/tests/performance_tests/hmat.hpp: In function 'int hmat(int, char**)':
/build/htool-0.1~git20191218/tests/performance_tests/hmat.hpp:131:52: error: expected primary-expression before ',' token
  131 |  HA.save_infos((outputpath+"/"+outputfile).c_str(),,std::ios::app,": ");
      |                                                    ^
make[2]: *** [tests/performance_tests/CMakeFiles/Hmat_fullACA.dir/build.make:66: tests/performance_tests/CMakeFiles/Hmat_fullACA.dir/hmat_fullACA.cpp.o] Error 1
```

**Comment by PierreMarchand20** [comment]
Thank you, I fixed it. I should at least add the compilation of this test in Travis I guess. 

FYI, you do not need to compile this file except if you want to use it.

**Comment by Trophime** [comment]
Dunno if it's related but:

88% tests passed, 6 tests failed out of 49

Total Test time (real) =   4.83 sec

The following tests FAILED:
	 42 - Test_hmat_vec_prod_1 (Failed)
	 43 - Test_hmat_vec_prod_2 (Failed)
	 44 - Test_hmat_vec_prod_4 (Failed)
	 45 - Test_hmat_mat_prod_1 (Failed)
	 46 - Test_hmat_mat_prod_2 (Failed)
	 47 - Test_hmat_mat_prod_4 (Failed)
Errors while running CTest
make[2]: *** [Makefile:133: test] Error 8

**Comment by PierreMarchand20** [comment]
That is interesting, I have no issue on Travis and I test several configurations. Did you try with the current master branch ?

If yes, could you run `ctest —output-on-failure‘ to get more verbose.

**Comment by Trophime** [comment]
I ran the tests with develop branch on debian Bullseye.
I will try to send you the logs as soon as I will be back to my office..
Best

**Comment by PierreMarchand20** [comment]
Great thank you !

**Comment by PierreMarchand20** [comment]
Do you have any more information about this issue ?

**Comment by PierreMarchand20** [comment]
Do not hesitate to open it again if you have anything new.
